spring.application.name=pet-ops-commerce
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petops}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:petops}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:petops}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration