-- 회원 기본 정보 테이블
create table members (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    name varchar(100) not null,
    role varchar(30) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_members_email unique (email)
);

-- 회원의 반려동물 프로필 테이블
create table pet_profiles (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    name varchar(100) not null,
    species varchar(50) not null,
    birth_date date,
    allergy_notes text,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp
);

-- 상품 카테고리 테이블
create table product_categories (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    display_order integer not null default 0,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp
);

-- 판매 상품 테이블
create table products (
    id bigint generated by default as identity primary key,
    category_id bigint not null,
    name varchar(200) not null,
    description text,
    price integer not null,
    sale_status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_products_price_non_negative check (price >= 0)
);

-- 상품별 LOT 관리 테이블
-- lot_key는 사용자가 확인할 수 있는 LOT 업무 번호입니다.
-- lot3: 유효기간, lot4: 입고일자
create table lots (
    id bigint generated by default as identity primary key,
    lot_key varchar(50) not null,
    product_id bigint not null,
    lot1 varchar(100),
    lot2 varchar(100),
    lot3 date,
    lot4 date,
    lot5 varchar(100),
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_lots_lot_key unique (lot_key)
);

-- 재고를 보관하는 창고 테이블
create table warehouses (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    name varchar(100) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_warehouses_code unique (code)
);

-- 상품, 창고, location, LOT 단위 현재 재고 테이블
-- total_quantity = available_quantity + working_quantity 기준으로 관리합니다.
create table stocks (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    warehouse_id bigint not null,
    location_id bigint not null,
    lot_id bigint not null,
    total_quantity integer not null,
    available_quantity integer not null,
    working_quantity integer not null default 0,
    version bigint not null default 0,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_stocks_product_warehouse_location_lot unique (product_id, warehouse_id, location_id, lot_id),
    constraint chk_stocks_total_quantity_non_negative check (total_quantity >= 0),
    constraint chk_stocks_available_quantity_non_negative check (available_quantity >= 0),
    constraint chk_stocks_working_quantity_non_negative check (working_quantity >= 0),
    constraint chk_stocks_total_equals_working_plus_available check (total_quantity = working_quantity + available_quantity)
);

-- 주문 기본 정보 테이블
create table orders (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    order_no varchar(50) not null,
    order_type varchar(30) not null default 'CUSTOMER_ORDER',
    status varchar(30) not null,
    total_amount integer not null,
    discount_amount integer not null default 0,
    payment_amount integer not null,
    ordered_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_orders_order_no unique (order_no),
    constraint chk_orders_total_amount_non_negative check (total_amount >= 0),
    constraint chk_orders_discount_amount_non_negative check (discount_amount >= 0),
    constraint chk_orders_payment_amount_non_negative check (payment_amount >= 0)
);


-- 고객 주문 배송 정보 테이블
-- 배송지/수령인/배송 요청사항은 주문 본문과 분리해 관리합니다.
create table order_deliveries (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    recipient_name varchar(100) not null,
    recipient_phone varchar(30) not null,
    zip_code varchar(20),
    address1 varchar(255) not null,
    address2 varchar(255),
    delivery_message varchar(500),
    entrance_password varchar(100),
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_order_deliveries_order_id unique (order_id)
);

-- 주문 상품 목록 테이블
create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    unit_price integer not null,
    line_amount integer not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_order_items_quantity_positive check (quantity > 0),
    constraint chk_order_items_unit_price_non_negative check (unit_price >= 0),
    constraint chk_order_items_line_amount_non_negative check (line_amount >= 0)
);

-- 주문 결제 정보 테이블
create table payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    payment_key varchar(255),
    status varchar(30) not null,
    amount integer not null,
    approved_at timestamp,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_payments_order_id unique (order_id),
    constraint chk_payments_amount_non_negative check (amount >= 0)
);

-- 쿠폰 마스터 테이블
create table coupons (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    discount_type varchar(30) not null,
    discount_value integer not null,
    min_order_amount integer not null default 0,
    starts_at timestamp not null,
    ends_at timestamp not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_coupons_discount_value_non_negative check (discount_value >= 0),
    constraint chk_coupons_min_order_amount_non_negative check (min_order_amount >= 0)
);

-- 주문 상태 변경 및 운영 이벤트 이력 테이블
create table order_events (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    event_type varchar(50) not null,
    description varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp
);

-- 회원별 반려동물 조회 인덱스
create index idx_pet_profiles_member_id on pet_profiles (member_id);

-- 상품 목록 필터 인덱스
create index idx_products_category_status on products (category_id, sale_status);

-- 상품별 LOT 조회 인덱스
create index idx_lots_product_id on lots (product_id);

-- LOT 유효기간 조회 인덱스
create index idx_lots_lot3 on lots (lot3);

-- LOT 입고일자 조회 인덱스
create index idx_lots_lot4 on lots (lot4);

-- 상품별 재고 조회 인덱스
create index idx_stocks_product_id on stocks (product_id);

-- 창고별 재고 조회 인덱스
create index idx_stocks_warehouse_id on stocks (warehouse_id);

-- LOT별 재고 조회 인덱스
create index idx_stocks_lot_id on stocks (lot_id);

-- location별 재고 조회 인덱스
create index idx_stocks_location_id on stocks (location_id);

-- 회원별 주문 내역 시간순 조회 인덱스
create index idx_orders_member_ordered_at on orders (member_id, ordered_at);

-- 주문 배송 정보 조회 인덱스
create index idx_order_deliveries_order_id on order_deliveries (order_id);

-- 주문별 상품 목록 조회 인덱스
create index idx_order_items_order_id on order_items (order_id);

-- 상품별 주문 상품 조회 인덱스
create index idx_order_items_product_id on order_items (product_id);

-- 주문별 이벤트 시간순 조회 인덱스
create index idx_order_events_order_created_at on order_events (order_id, created_at);