-- 창고 안의 실제 보관/작업 위치 테이블
-- STAGE: 입고 대기장, NORMAL: 일반 보관 위치, PICKTO: 피킹 후 출고 전 대기 위치
create table locations (
    id bigint generated by default as identity primary key,
    warehouse_id bigint not null,
    code varchar(50) not null,
    name varchar(100) not null,
    location_type varchar(30) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_locations_warehouse_code unique (warehouse_id, code)
);

-- 창고별 location 조회 인덱스
create index idx_locations_warehouse_id on locations (warehouse_id);