-- 창고 안의 실제 보관/작업 위치 테이블
-- STORAGE: 일반 보관 위치, PICKTO: 피킹 후 출고 전 대기 위치
create table locations (
    id bigint generated by default as identity primary key,
    warehouse_id bigint not null,
    code varchar(50) not null,
    name varchar(100) not null,
    location_type varchar(30) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    constraint uk_locations_warehouse_code unique (warehouse_id, code)
);

-- 기존 현재고 수량 컬럼을 총수량 의미로 명확히 변경합니다.
alter table stocks rename column quantity to total_quantity;

-- 기존 check constraint 이름을 새 컬럼 의미에 맞게 변경합니다.
alter table stocks rename constraint chk_stocks_quantity_non_negative to chk_stocks_total_quantity_non_negative;

-- 할당, 피킹, 출고 작업 중인 수량입니다.
-- 가용수량은 total_quantity - working_quantity로 계산합니다.
alter table stocks add column working_quantity integer not null default 0;

-- 동일 창고 안에서도 Rack/피킹 위치별 재고를 분리하기 위한 location_id입니다.
alter table stocks add column location_id bigint;

-- 이미 재고 데이터가 있는 개발 DB를 위해 창고별 기본 location을 생성합니다.
insert into locations (warehouse_id, code, name, location_type, status)
select distinct stock_source.warehouse_id, 'DEFAULT', 'Default Location', 'STORAGE', 'ACTIVE'
from stocks stock_source
where not exists (
    select 1
    from locations existing_location
    where existing_location.warehouse_id = stock_source.warehouse_id
      and existing_location.code = 'DEFAULT'
);

-- 기존 재고가 있다면 창고별 기본 location에 연결합니다.
update stocks stock_target
set location_id = default_location.id
from locations default_location
where default_location.warehouse_id = stock_target.warehouse_id
  and default_location.code = 'DEFAULT'
  and stock_target.location_id is null;

-- 신규 구조에서는 stock이 반드시 location을 가져야 합니다.
alter table stocks alter column location_id set not null;

-- 작업수량은 음수가 될 수 없고, 총수량보다 클 수 없습니다.
alter table stocks add constraint chk_stocks_working_quantity_non_negative check (working_quantity >= 0);
alter table stocks add constraint chk_stocks_working_quantity_lte_total check (working_quantity <= total_quantity);

-- location 단위 재고 중복을 막기 위해 기존 unique 기준을 location 포함 기준으로 교체합니다.
alter table stocks drop constraint uk_stocks_product_warehouse_lot;
alter table stocks add constraint uk_stocks_product_warehouse_location_lot unique (product_id, warehouse_id, location_id, lot_id);

-- 창고별 location 조회 인덱스
create index idx_locations_warehouse_id on locations (warehouse_id);

-- location별 재고 조회 인덱스
create index idx_stocks_location_id on stocks (location_id);
