-- 업무 번호 생성 규칙 테이블
-- 주문번호, 결제번호, 출고번호처럼 사람이 확인하는 번호의 포맷을 관리합니다.
create table business_number_rules (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    prefix varchar(30) not null,
    date_format varchar(30),
    sequence_width integer not null,
    reset_cycle varchar(30) not null,
    scope_type varchar(30) not null,
    separator varchar(10) not null default '-',
    allocation_size integer not null default 100,
    enabled boolean not null default true,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_business_number_rules_code unique (code),
    constraint chk_business_number_rules_sequence_width_positive check (sequence_width > 0),
    constraint chk_business_number_rules_allocation_size_positive check (allocation_size > 0)
);

-- 업무 번호 현재 구간 시작값 테이블
-- next_value는 다음에 할당할 번호 구간의 시작값입니다.
create table business_number_sequences (
    id bigint generated by default as identity primary key,
    rule_code varchar(50) not null,
    scope_key varchar(100) not null,
    sequence_period varchar(30) not null,
    next_value bigint not null,
    version bigint not null default 0,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_business_number_sequences_key unique (rule_code, scope_key, sequence_period),
    constraint chk_business_number_sequences_next_value_positive check (next_value > 0)
);

-- 업무 번호 규칙 조회 인덱스
create index idx_business_number_rules_enabled on business_number_rules (enabled);

-- 업무 번호 구간 조회 인덱스
create index idx_business_number_sequences_rule_scope_period
    on business_number_sequences (rule_code, scope_key, sequence_period);

-- 주문번호 기본 규칙
-- 예: ORD-20260625-000001
insert into business_number_rules (
    code,
    prefix,
    date_format,
    sequence_width,
    reset_cycle,
    scope_type,
    separator,
    allocation_size,
    enabled
) values (
    'ORDER',
    'ORD',
    'yyyyMMdd',
    6,
    'DAILY',
    'GLOBAL',
    '-',
    100,
    true
);