-- 기존 단일 수량 기준 재고 이력 테이블은 stock_movements 원장 구조로 대체합니다.
drop index if exists idx_stock_histories_stock_created_at;
drop table if exists stock_histories;

-- 재고 작업 헤더 테이블
-- 출고, 재고조정, 재고이동, 입고 같은 작업 묶음의 현재 상태를 관리합니다.
create table stock_jobs (
    id bigint generated by default as identity primary key,
    job_no varchar(50) not null,
    job_type varchar(30) not null,
    warehouse_id bigint not null,
    reference_type varchar(30),
    reference_id bigint,
    status varchar(30) not null,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    constraint uk_stock_jobs_job_no unique (job_no)
);

-- 재고 이동 원장 테이블
-- quantity는 해당 location 기준 증감 방향을 부호로 표현합니다.
-- total/working delta는 stocks row의 수량 변경 내용을 감사 로그로 남깁니다.
create table stock_movements (
    id bigint generated by default as identity primary key,
    job_id bigint not null,
    job_no varchar(50) not null,
    stock_id bigint not null,
    movement_type varchar(30) not null,
    warehouse_id bigint not null,
    location_id bigint not null,
    from_location_id bigint,
    to_location_id bigint,
    product_id bigint not null,
    lot_id bigint not null,
    quantity integer not null,
    total_quantity_delta integer not null,
    working_quantity_delta integer not null,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    constraint chk_stock_movements_quantity_not_zero check (quantity <> 0)
);

create index idx_stock_jobs_reference on stock_jobs (reference_type, reference_id);
create index idx_stock_jobs_status on stock_jobs (status);
create index idx_stock_movements_job_id on stock_movements (job_id);
create index idx_stock_movements_stock_created_at on stock_movements (stock_id, created_at);
create index idx_stock_movements_product_lot on stock_movements (product_id, lot_id);
