-- 재고 작업 헤더 테이블
-- 출고처럼 단계가 있는 작업의 현재 상태와 즉시 완료 작업의 완료 시각을 관리합니다.
create table stock_jobs (
    id bigint generated by default as identity primary key,
    job_no varchar(50) not null,
    job_type varchar(30) not null,
    warehouse_id bigint not null,
    reference_type varchar(30),
    reference_id bigint,
    status varchar(30) not null,
    reason varchar(500),
    completed_at timestamp,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_stock_jobs_job_no unique (job_no)
);

-- 재고 이동 원장 테이블
-- quantity는 처리 수량, total_quantity는 처리 후 해당 stock row의 총수량 snapshot입니다.
-- from/to location은 이동 방향 또는 기준 location을 표현합니다.
create table stock_movements (
    id bigint generated by default as identity primary key,
    job_id bigint not null,
    job_no varchar(50) not null,
    stock_id bigint not null,
    movement_type varchar(30) not null,
    warehouse_id bigint not null,
    product_id bigint not null,
    lot_id bigint not null,
    from_location_id bigint,
    to_location_id bigint,
    quantity integer not null,
    total_quantity integer not null,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_stock_movements_quantity_not_zero check (quantity <> 0)
);

create index idx_stock_jobs_reference on stock_jobs (reference_type, reference_id);
create index idx_stock_jobs_status on stock_jobs (status);
create index idx_stock_jobs_completed_at on stock_jobs (completed_at);
create index idx_stock_movements_job_id on stock_movements (job_id);
create index idx_stock_movements_stock_created_at on stock_movements (stock_id, created_at);
create index idx_stock_movements_product_lot on stock_movements (product_id, lot_id);
create index idx_stock_movements_from_location on stock_movements (from_location_id);
create index idx_stock_movements_to_location on stock_movements (to_location_id);