-- 관리자 판매 주문 테이블
-- 고객 주문을 운영자가 확정한 내부 판매 기준 주문입니다.
create table sales_orders (
    id bigint generated by default as identity primary key,
    sales_order_no varchar(50) not null,
    order_id bigint not null,
    status varchar(30) not null,
    confirmed_at timestamp,
    canceled_at timestamp,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_sales_orders_sales_order_no unique (sales_order_no)
);

-- 관리자 판매 주문 품목 테이블
-- 고객 주문 품목을 내부 판매 주문 품목으로 확정한 snapshot입니다.
create table sales_order_items (
    id bigint generated by default as identity primary key,
    sales_order_id bigint not null,
    order_item_id bigint not null,
    product_id bigint not null,
    order_quantity integer not null,
    unit_price integer not null,
    line_amount integer not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_sales_order_items_order_quantity_positive check (order_quantity > 0),
    constraint chk_sales_order_items_unit_price_non_negative check (unit_price >= 0),
    constraint chk_sales_order_items_line_amount_non_negative check (line_amount >= 0)
);

-- 창고 출고 주문 테이블
-- 판매 주문 확정 후 창고가 수행할 출고 지시입니다.
create table shipment_orders (
    id bigint generated by default as identity primary key,
    shipment_order_no varchar(50) not null,
    sales_order_id bigint not null,
    warehouse_id bigint not null,
    status varchar(30) not null,
    scheduled_ship_date date,
    shipped_at timestamp,
    canceled_at timestamp,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_shipment_orders_shipment_order_no unique (shipment_order_no)
);

-- 창고 출고 주문 품목 테이블
-- 할당/피킹/출고 수량은 품목 단위로 누적 관리합니다.
create table shipment_order_items (
    id bigint generated by default as identity primary key,
    shipment_order_id bigint not null,
    sales_order_item_id bigint not null,
    product_id bigint not null,
    order_quantity integer not null,
    allocated_quantity integer not null default 0,
    picked_quantity integer not null default 0,
    shipped_quantity integer not null default 0,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_shipment_items_order_quantity_positive check (order_quantity > 0),
    constraint chk_shipment_items_allocated_quantity_non_negative check (allocated_quantity >= 0),
    constraint chk_shipment_items_picked_quantity_non_negative check (picked_quantity >= 0),
    constraint chk_shipment_items_shipped_quantity_non_negative check (shipped_quantity >= 0),
    constraint chk_shipment_items_allocated_lte_order check (allocated_quantity <= order_quantity),
    constraint chk_shipment_items_picked_lte_allocated check (picked_quantity <= allocated_quantity),
    constraint chk_shipment_items_shipped_lte_picked check (shipped_quantity <= picked_quantity)
);

-- 공급사 구매 발주 테이블
-- 운영사가 공급사에 상품을 발주하는 주문입니다.
create table purchase_orders (
    id bigint generated by default as identity primary key,
    purchase_order_no varchar(50) not null,
    supplier_name varchar(100),
    status varchar(30) not null,
    ordered_at timestamp not null,
    confirmed_at timestamp,
    canceled_at timestamp,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_purchase_orders_purchase_order_no unique (purchase_order_no)
);

-- 공급사 구매 발주 품목 테이블
create table purchase_order_items (
    id bigint generated by default as identity primary key,
    purchase_order_id bigint not null,
    product_id bigint not null,
    order_quantity integer not null,
    unit_price integer not null default 0,
    line_amount integer not null default 0,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_purchase_order_items_order_quantity_positive check (order_quantity > 0),
    constraint chk_purchase_order_items_unit_price_non_negative check (unit_price >= 0),
    constraint chk_purchase_order_items_line_amount_non_negative check (line_amount >= 0)
);

-- 창고 입고 처리 주문 테이블
-- 구매 발주 확정 후 창고가 수행할 receiving 지시입니다.
create table receiving_orders (
    id bigint generated by default as identity primary key,
    receiving_order_no varchar(50) not null,
    purchase_order_id bigint not null,
    warehouse_id bigint not null,
    status varchar(30) not null,
    scheduled_receive_date date,
    received_at timestamp,
    canceled_at timestamp,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_receiving_orders_receiving_order_no unique (receiving_order_no)
);

-- 창고 입고 처리 주문 품목 테이블
-- 입고 예정 수량과 확정 수량, LOT 예정 정보를 품목 단위로 관리합니다.
create table receiving_order_items (
    id bigint generated by default as identity primary key,
    receiving_order_id bigint not null,
    purchase_order_item_id bigint not null,
    product_id bigint not null,
    lot_id bigint,
    order_quantity integer not null,
    received_quantity integer not null default 0,
    lot1 varchar(100),
    lot2 varchar(100),
    lot3 date,
    lot4 date,
    lot5 varchar(100),
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    deleted_at timestamp,
    constraint chk_receiving_items_order_quantity_positive check (order_quantity > 0),
    constraint chk_receiving_items_received_quantity_non_negative check (received_quantity >= 0),
    constraint chk_receiving_items_received_lte_order check (received_quantity <= order_quantity)
);

create index idx_sales_orders_order_id on sales_orders (order_id);
create index idx_sales_orders_status on sales_orders (status);
create index idx_sales_order_items_sales_order_id on sales_order_items (sales_order_id);
create index idx_sales_order_items_order_item_id on sales_order_items (order_item_id);
create index idx_shipment_orders_sales_order_id on shipment_orders (sales_order_id);
create index idx_shipment_orders_warehouse_status on shipment_orders (warehouse_id, status);
create index idx_shipment_order_items_shipment_order_id on shipment_order_items (shipment_order_id);
create index idx_purchase_orders_status_ordered_at on purchase_orders (status, ordered_at);
create index idx_purchase_order_items_purchase_order_id on purchase_order_items (purchase_order_id);
create index idx_receiving_orders_purchase_order_id on receiving_orders (purchase_order_id);
create index idx_receiving_orders_warehouse_status on receiving_orders (warehouse_id, status);
create index idx_receiving_order_items_receiving_order_id on receiving_order_items (receiving_order_id);