-- 재고 현재고 안전재고 컬럼 제거
-- 안전재고는 stock row 단위가 아니라 상품/창고 정책 단위에서 다루는 값이므로 현재고에서 제거합니다.
alter table stocks drop constraint if exists chk_stocks_safety_quantity_non_negative;
alter table stocks drop column if exists safety_quantity;

-- 재고 작업 헤더 컬럼 순서와 완료/삭제 시각 정리
-- completed_at은 작업 완료 여부, deleted_at은 작업 헤더 숨김 처리 용도로 사용합니다.
create table stock_jobs_cleanup (
    id bigint generated by default as identity primary key,
    job_no varchar(50) not null,
    job_type varchar(30) not null,
    warehouse_id bigint not null,
    reference_type varchar(30),
    reference_id bigint,
    status varchar(30) not null,
    reason varchar(500),
    completed_at timestamp,
    deleted_at timestamp,
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_at timestamp not null default current_timestamp,
    updated_by bigint,
    constraint uk_stock_jobs_cleanup_job_no unique (job_no)
);

insert into stock_jobs_cleanup (
    id,
    job_no,
    job_type,
    warehouse_id,
    reference_type,
    reference_id,
    status,
    reason,
    completed_at,
    deleted_at,
    created_at,
    created_by,
    updated_at,
    updated_by
)
select
    id,
    job_no,
    job_type,
    warehouse_id,
    reference_type,
    reference_id,
    case
        when job_type = 'INBOUND' then 'RECEIVED'
        when job_type = 'ADJUSTMENT' then 'ADJUSTED'
        when job_type = 'TRANSFER' then 'TRANSFERRED'
        else status
    end as status,
    reason,
    case
        when job_type in ('INBOUND', 'ADJUSTMENT', 'TRANSFER') then coalesce(updated_at, created_at)
        when status = 'SHIPPED' then coalesce(updated_at, created_at)
        else null
    end as completed_at,
    null as deleted_at,
    created_at,
    created_by,
    updated_at,
    updated_by
from stock_jobs;

drop table stock_jobs;
alter table stock_jobs_cleanup rename to stock_jobs;
alter table stock_jobs rename constraint uk_stock_jobs_cleanup_job_no to uk_stock_jobs_job_no;

select setval(pg_get_serial_sequence('stock_jobs', 'id'), coalesce((select max(id) from stock_jobs), 1), (select count(*) > 0 from stock_jobs));

create index idx_stock_jobs_reference on stock_jobs (reference_type, reference_id);
create index idx_stock_jobs_status on stock_jobs (status);
create index idx_stock_jobs_completed_at on stock_jobs (completed_at);

-- 재고 이동 원장 컬럼 정리
-- quantity는 처리 수량, total_quantity는 처리 후 해당 stock row의 총수량 snapshot입니다.
-- from/to location은 이동 방향 또는 기준 location만 표현하고 location_id 중복 컬럼은 제거합니다.
create table stock_movements_cleanup (
    id bigint generated by default as identity primary key,
    job_id bigint not null,
    job_no varchar(50) not null,
    stock_id bigint not null,
    movement_type varchar(30) not null,
    warehouse_id bigint not null,
    product_id bigint not null,
    lot_id bigint not null,
    from_location_id bigint,
    to_location_id bigint,
    quantity integer not null,
    total_quantity integer not null,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    created_by bigint,
    constraint chk_stock_movements_quantity_not_zero check (quantity <> 0)
);

insert into stock_movements_cleanup (
    id,
    job_id,
    job_no,
    stock_id,
    movement_type,
    warehouse_id,
    product_id,
    lot_id,
    from_location_id,
    to_location_id,
    quantity,
    total_quantity,
    reason,
    created_at,
    created_by
)
select
    id,
    job_id,
    job_no,
    stock_id,
    movement_type,
    warehouse_id,
    product_id,
    lot_id,
    case
        when movement_type in ('ADJUST', 'ALLOCATE') then location_id
        else from_location_id
    end as from_location_id,
    case
        when movement_type in ('ADJUST', 'ALLOCATE') then null
        else to_location_id
    end as to_location_id,
    quantity,
    sum(total_quantity_delta) over (partition by stock_id order by id rows between unbounded preceding and current row) as total_quantity,
    reason,
    created_at,
    created_by
from stock_movements;

drop table stock_movements;
alter table stock_movements_cleanup rename to stock_movements;

select setval(pg_get_serial_sequence('stock_movements', 'id'), coalesce((select max(id) from stock_movements), 1), (select count(*) > 0 from stock_movements));

create index idx_stock_movements_job_id on stock_movements (job_id);
create index idx_stock_movements_stock_created_at on stock_movements (stock_id, created_at);
create index idx_stock_movements_product_lot on stock_movements (product_id, lot_id);
create index idx_stock_movements_from_location on stock_movements (from_location_id);
create index idx_stock_movements_to_location on stock_movements (to_location_id);